# Generated by Django 4.1.7 on 2023-06-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
